### PR TITLE
Fake req.socket to fix stdlib death on req.resume()

### LINKED ISSUE #29: Failure on 0.10 with Express 3.20
With this test:

```
var test = require('tape');

var shot = require('shot');

var app = require('express')();

test('works?', function (t) {
    shot.inject(app, {url: '/'}, function (res) {
        t.end();
    });
});
```

I get 

```
TAP version 13
# works?

http.js:348
  if (this.socket.readable)
                 ^
TypeError: Cannot read property 'readable' of undefined
    at IncomingMessage._read (http.js:348:18)
    at IncomingMessage.Readable.read (_stream_readable.js:341:10)
    at IncomingMessage.read (http.js:340:15)
    at IncomingMessage.<anonymous> (_stream_readable.js:764:45)
    at IncomingMessage.emit (events.js:92:17)
    at emitDataEvents (_stream_readable.js:790:10)
    at IncomingMessage.Readable.resume (_stream_readable.js:734:3)
    at send (/Users/ariastewart/Projects/adaro/node_modules/express/node_modules/connect/node_modules/finalhandler/index.js:139:7)
    at Object.<anonymous> (/Users/ariastewart/Projects/adaro/node_modules/express/node_modules/connect/node_modules/finalhandler/index.js:96:5)
    at Object.immediate._onImmediate (timers.js:372:16)
```

### PR DESCRIPTION
**Pull request by garthk**
Fixes #29.

### CODE REVIEW

**Comment by garthk** [comment]
My `get` tests are OK, but `post` with `payload` not so much. We end up hanging in `raw-body` with `stream` as the `shot` request object:

```
  stream.on('data', onData)
  stream.once('end', onEnd)
  stream.once('error', onEnd)
  stream.once('close', cleanup)
```

… and none of the events fire. The stream is `readable`, `flowing`, and not `ended`. I'd guess it's paused but throwing in a `resume` doesn't help.

**Comment by hueniverse** [comment]
Try @chrisdickinson

**Comment by mtharrison** [comment]
Hey @garthk, do you have a minimal failing test for this issue that I can run and see it myself? I checked the test in the first comment of the original issue against the versions of express you stated in your comment and they work fine.

**Comment by mtharrison** [comment]
If the solution really is to add a `socket` property to our `Request` object there's probably a better solution. 

We already have a `connection` property and `this.connection === this.socket` for `Http.ClientRequest`, so we can probably just do:

```javascript
this.socket = this.connection = {
    remoteAddress: options.remoteAddress || '127.0.0.1'
};
```

If this fixes this issue, I see no reason not to add it.

**Comment by hueniverse** [comment]
This should be resolved.

**Pull request closed without merging**
