### PR TITLE
Inject request with specified the remote client IP address

### LINKED ISSUE #35: Client IP address
Is it possible to specify what the IP address of the client making the fake request should appear to be?  

E.g. so we can control what `request.info.remoteAddress` is populated with.

### PR DESCRIPTION
**Pull request by matteobaglini**
fixes #35 issue

### CODE REVIEW

**Comment by mtharrison** [comment]
@matteobaglini thanks for your PR. [`request.info`](http://hapijs.com/api#request-properties) is something that's found on the hapi `request` object. 

The `request` in this module is supposed to simulate node's [`http.IncomingMessage`](https://nodejs.org/api/http.html#http_http_incomingmessage). The ip address should therefore be on `req.connection.remoteAddress`.

**Comment by matteobaglini** [comment]
@mtharrison I changed the implementation following your suggestion.

**Comment by mtharrison** [comment]
@matteobaglini Would you be able to update the readme too with this new option?

**Comment by mtharrison** [comment]
@hueniverse This is going to break all of hapi's tests so am I right in assuming we:
- Bump the major version of shot
- Upgrade hapi's shot version and fix the tests over there

**Comment by hueniverse** [comment]
Why does it break existing tests? Why is it setting a default value of `''`?

**Comment by mtharrison** [comment]
It's due to a check [here](https://github.com/hapijs/hapi/blob/master/lib/connection.js#L223-L227) that bails out of processing a request on a stopped server if there's a `connection` property. 

I'm guessing that checking for `connection` was a way of checking if the request is coming from Shot. A better way might be for us to use `Shot.isInjection(request)`.

**Comment by matteobaglini** [comment]
@mtharrison after you, or @hueniverse, released a new Shot version, I can help to fix Hapi's broken tests with a PR.

**Comment by hueniverse** [comment]
If that's the only change required, I would not consider it a breaking change.

**Comment by mtharrison** [comment]
@hueniverse ah ok. I just spotted that hapi is linked to a specific version of Shot via the shrinkwrap. I assumed that releasing this under 1.x.x would break everyone's hapi.

In that case, we're good to release Shot 1.6.0, and update hapi later?

**Comment by hueniverse** [comment]
Yes.

**Pull request merged**
